### ISSUE TITLE
Implement graphical user application

### ISSUE THREAD

**Issue by SundarKrishnakumar** [cu-ecen-aeld/final-project-SundarKrishnakumar#10]
**1. Create a graphical user application to visualize ADC data. ** 

- [x] **DoD:** GUI is implemented and ADC chip's data is visible in the GUI. Values are updated automatically with respect to any change in input voltage.

Blocker:  #9

**Comment by rajatchaple** [comment]
I've been learning to develop a GUI using Tkinter library from python. 
I've also been looking for ways to integrate required packages using buildroot.

I have dependency on sysfs driver Implementation (#9 ) which would act as handles for python based GUI.

**Comment by rajatchaple** [comment]
To display a GUI, desktop would be required. For this, X11 (X server) is being used.
However, there is an error while detecting the display connected over HDMI. 
Error: No screens found

![X server bug](https://user-images.githubusercontent.com/77606072/142813248-d121e1fd-4811-47d6-b1e1-fc336033fe30.JPG)


Log also mentions 'No Device found'. Working on setting up the correct configuration to get the display detected.

commit link: https://github.com/cu-ecen-aeld/final-project-SundarKrishnakumar/tree/master/base_external/configs

**Comment by rajatchaple** [comment]
Going with Approach1, python was installed on target system

![python3 installation](https://user-images.githubusercontent.com/77606072/142816344-0a2f1b64-ec41-41a6-b74d-2c06b1d1ce58.JPG)

Also, instructions at
**18.8.3. Generating a python-package from a PyPI repository**  from buildroot manual page https://buildroot.org/downloads/manual/manual.html#_infrastructure_for_python_packages
was used to install required packages.
e.g. python tkinter library
commit link: https://github.com/cu-ecen-aeld/final-project-SundarKrishnakumar/tree/master/base_external/configs

However, this approach was discarded as Display wasn't successfully integrated.

**Comment by rajatchaple** [comment]
Two days back, Sundar pushed his sysfs implementation which gives dummy data. This was enough to get started on my GUI application.

Approach 2: Reading data over serial from beaglebone black and displaying it over GUI on host machine

![gui](https://user-images.githubusercontent.com/77606072/142814775-9782e1de-50c3-4c8d-b25c-60a40553ccc3.png)

GUI sends command over serial to read spi read value through sysfs class.

Commit link: https://github.com/cu-ecen-aeld/final-project-rajatchaple/tree/main/code/gui

There is noticeable lag while reading these values. GUI code would be improved in following week.

DoD checked: Implemented GUI shows updated data from the ADC chip
