### ISSUE TITLE
SPI HW setup on BBB

### ISSUE THREAD

**Issue by SundarKrishnakumar** [cu-ecen-aeld/final-project-SundarKrishnakumar#2]
**1. Enable SPI on the Beaglebone Black running bare Linux built using buildroot** 

- [x] **DoD:** SPI closed loop test passes.
Blockers: <br> #3 <br> #4 

**2. Make any necessary kernel modifications like setting HWMOD_NO_IDLE flag for the SPI hardware module** 

- [x] **DoD:** SPI closed loop test passes.
Blockers: <br> #3 <br> #4

**Comment by rajatchaple** [comment]
SPI closed loop test successful. We found that when no user is there for the SPI hardware module, the kernel cuts off the clock to the module. To prevent this we have added the flag  HWMOD_NO_IDLE to the module. Created a patch for this modification.
Patch link: https://github.com/cu-ecen-aeld/final-project-SundarKrishnakumar/blob/master/base_external/patches/linux/spi_no_idle.patch
Closed loop test - https://github.com/cu-ecen-aeld/final-project-rajatchaple/blob/main/images/closed_loop_test.png
