### ISSUE TITLE
SPI character driver-Initial implementation

### ISSUE THREAD

**Issue by SundarKrishnakumar** [cu-ecen-aeld/final-project-SundarKrishnakumar#3]
**1. Create an initial and simple implementation of SPI character driver/SPI client driver, targeting MCP3002 ADC chip.** 

- [x] **DoD:** The userspace application like the 'cat' utility can successfully communicate with the SPI character driver.

**Comment by rajatchaple** [comment]
Tested and verified with closed loop test. As per plan, testing on ADC chip would be done in sprint 2.
SPI closed loop test - 'h' was sent over MOSI and received over MISO. cat command initiated this test and displayed 'h' on the terminal.
https://github.com/cu-ecen-aeld/final-project-rajatchaple/blob/main/images/closed_loop_test.png
