### ISSUE TITLE
Device Tree source file

### ISSUE THREAD

**Issue by SundarKrishnakumar** [cu-ecen-aeld/final-project-SundarKrishnakumar#5]
**1. Create a device tree source (DTS) file describing the SPI hardware module and ADC chip device** 

- [x] **DoD:**probe() function in low_level_driver.c  and adc_char_driver.c gets invoked.

Blockers: None

**Comment by rajatchaple** [comment]
Probe function invoked for both adc_char_driver and low_level driver once this patch was implemented.

challenges faced while creating kernel patch:
compatible property for the patch may contain commas while considering platform bus driver (low level driver) as it is separateed by "". However, for aesd_char_driver's name property, string is separated by commas.
e.g. 
"mcp,mcp3002" -> single string for platform bus driver
"mcp,mcp3002" -> multiple strings (mcp and mcp3002) for aesd_char_driver

It required significant amount of reading to identify this bug.

documentation: https://github.com/cu-ecen-aeld/final-project-rajatchaple/blob/main/docs/adv-driver-1.md
patch link: https://github.com/cu-ecen-aeld/final-project-SundarKrishnakumar/blob/master/base_external/patches/linux/devtree.patch
functionality test: https://github.com/cu-ecen-aeld/final-project-rajatchaple/blob/main/images/probe.JPG
